/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject2;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author simou
 */
public class app1 extends javax.swing.JFrame  {
   static  String username="root";
    static String passwd="";
   static  String conc="jdbc:mysql://localhost/simou";
  static  Connection k;
   static Statement n;
   static  ResultSet d;
   
    public app1() {
        initComponents();
        setVisible(true);
         addPlanceholderStyle(jTextField1);
         addPlanceholderStyle(jPasswordField1);
        add(jMenu4);        
    }
    public static  Connection  connectionDB(){
           
             try{ 
           k=DriverManager.getConnection(conc, username, passwd);
              
             
             System.out.print("good connection");
             return k;
             }
              catch(SQLException e ){
           e.printStackTrace();
              return null;}
           
       }
    public  static void LireDB(String table){
        try{ 
        String l="select * from "+table+" where  gmail="+"\""+gmail+"\""+" and passwd="+"\""+passw+"\"";
          k=connectionDB();
          n=k.createStatement();
         d= n.executeQuery(l);
         while(d.next())
           {
             Ngmail=d.getString("gmail");
             Npasswd=d.getString("passwd");
             
                
           }
            
        }
          catch(SQLException e ){
           e.printStackTrace();
             }
      
     }
    public void addPlanceholderStyle(JTextField txt){
         Font font=txt.getFont();
         font=font.deriveFont(Font.ITALIC);
         txt.setFont(font);
         txt.setForeground(Color.gray);
         
     }
      public void removePlanceholderStyle(JTextField txt){
         Font font=txt.getFont();
         font=font.deriveFont(Font.BOLD);
         txt.setFont(font);
         txt.setForeground(Color.BLACK);
         
     }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jTextField3.setText("jTextField3");

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("sign up");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setText("Gmail");
        jTextField1.setToolTipText("");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPasswordField1.setText("passwd");
        jPasswordField1.setToolTipText("po");
        jPasswordField1.setEchoChar('\u0000');
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("connection");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("Mode pass oublier");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Sign Up");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel1))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("gmail is" +gmail);
        System.out.println(passw);
        LireDB("controleAcce");
         if(  ((Ngmail.equals(gmail)) ) && Npasswd.equals(passw))
                    {
                
                     JOptionPane.showMessageDialog(this, "GOOD","Message d’information",JOptionPane.INFORMATION_MESSAGE);
                       
                     
                    }
         else if(   !Ngmail.equals(gmail)  || (!Npasswd.equals(passw)))
                    {
                
                     JOptionPane.showMessageDialog(this, "Invalide Gmail or Passwd ","Message d’information",JOptionPane.ERROR_MESSAGE);
                       
                     
                    }
           else if(  gmail.equals("") && passw==null ){
     JOptionPane.showMessageDialog(this, "Please Enter PASSWD && Gmail","Message d’a",JOptionPane.ERROR_MESSAGE);

         }      
          
         else    if((passw==null &&  ! (gmail.equals("") ) ) || (passw==null &&   gmail.equals("") ) ){
       
             JOptionPane.showMessageDialog(this, "Please Enter PASSWD","Message d’avertissement",JOptionPane.ERROR_MESSAGE);
         }
         
         
         else  if(gmail.equals("") &&  Npasswd!=passw ){
       
             JOptionPane.showMessageDialog(this, "Please Enter gmail","Message d’avertissement",JOptionPane.ERROR_MESSAGE);
         }
         
         
         
             
             
   /* if(a== 0){
         JOptionPane.showMessageDialog(this, "Erreur ","Message d’avertissement",JOptionPane.ERROR_MESSAGE);
  
           app2 c =new app2();
            c.setVisible(true);
            this.setVisible(false);
        }  
      if(a==2){
         JOptionPane.showMessageDialog(this, "Vérifier PAS ","Message d’avertissement",JOptionPane.ERROR_MESSAGE);
     } */
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
        passw=jPasswordField1.getText();
        if(jPasswordField1.getText().length()==0){
         addPlanceholderStyle(jPasswordField1);
         jPasswordField1.setText("Passwd");
         
         
     }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        gmail=jTextField1.getText();
        if(jTextField1.getText().length()==0){
         addPlanceholderStyle(jTextField1);
         jTextField1.setText("Gmail");
         
         
     }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if(jTextField1.getText().equals("Gmail")){
         
         jTextField1.setText(null);
        // jTextField1.requestFocus();
         removePlanceholderStyle(jTextField1);
         
     }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
         jPasswordField1.setText(null);
         removePlanceholderStyle(jPasswordField1);
        
         
         
     
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
       
    }//GEN-LAST:event_formWindowGainedFocus

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setText("<html><a href=''>" +  "Mode pass oublier" + "</a></html>");
    }//GEN-LAST:event_jLabel1MouseEntered

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        app3 a =new app3();
        a.setVisible(true);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false );
        new app2().setVisible(true);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    static  String nom;
    static  String Prenom;
    static String gmail;
    static String passw;
   static  String Ngmail="";
  static  String Npasswd="";
   static String copassw;

    private void or(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}

