/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionnote;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author simou
 */
public class note extends javax.swing.JFrame implements DB{

    DefaultTableModel Model,Model2,Model3,Model4,Model5,Model6;
    Statement CreatST;
    Connection Cnx;
    ResultSet Result;
    static  String username="root";
   static String passwd="";
   static  String conc="jdbc:mysql://localhost/simou";
    
    public note() {
        initComponents();
        setVisible(true);
       // jComboBox1.setEditable(true);
        LireDB("Note");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jTable1.setBackground(new java.awt.Color(255, 204, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Prenom", "Branch", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 90, 390, 182);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(444, 324, 160, 30);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Chercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(297, 328, 120, 22);

        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(29, 53, 60, 16);

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(129, 50, 71, 22);

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(129, 101, 71, 22);

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(129, 159, 71, 22);

        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(129, 271, 71, 22);

        jLabel2.setText("Nom");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(29, 104, 27, 16);

        jLabel3.setText("Prenom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(29, 162, 60, 16);

        jLabel4.setText("Branch");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(29, 218, 50, 16);

        jLabel5.setText("Note");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(29, 271, 50, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INFO", "vhdl", "Linux", "Java" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(128, 215, 72, 22);

        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(11, 317, 90, 22);

        jButton3.setText("Actualise");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(129, 317, 100, 22);

        jButton4.setText("Modifier");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(11, 372, 90, 22);

        jButton5.setText("suprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(129, 372, 100, 22);

        jLabel6.setBackground(new java.awt.Color(255, 102, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel6.setText("Gestion De Note");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 20, 291, 38);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ajouter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("suprimer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
       
       recuperDATA("note");
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
       Model=(DefaultTableModel) jTable1.getModel();
       Model.setRowCount(0);
       String DATA[]={idST,Nom,Pre,Branch,note};
       ArrayList<String> data = LireDB("Note");
       
       if(jTextField2.isEditable()){
         /*  if(idST.equals(data.contains(idST))){
              JOptionPane.showMessageDialog(this,"Message d'avertissememnt ","déja inscrit",JOptionPane.WARNING_MESSAGE);
           }
           else{  */
             InsertDB("Note",idST,Nom,Pre,Branch,note);
           
             for (String id :data ){
                 if(id.equals(idST)){
                   JOptionPane.showMessageDialog(this,"Message d'avertissememnt ","déja inscrit",JOptionPane.WARNING_MESSAGE);
                 }
             }
             Model.addRow(DATA);
       }

//   }
       else {
           UpdateDB("Note");
       }
       
      
       
    }                                        
//Button Modifier 
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
     Model4=(DefaultTableModel) jTable1.getModel();
      Model4.setRowCount(0);
      ArrayList <String > data=LireDB("Note");
 
      if(data.contains(idST)){
          ModifyDB("Note");
      }
     if(idST.equals("")){
      IDste=JOptionPane.showInputDialog(this, "entrée votre ID","controle d'accée",JOptionPane.QUESTION_MESSAGE);
     
    //System.out.println(data);
    
    if(data.contains(IDste)){
       ModifyDB("Note");
    }}
    
    
        
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Model5=(DefaultTableModel)jTable1.getModel();
        System.out.print(IndexRow);
        if(IndexRow!=-1)
        Model5.removeRow(IndexRow);
        DeleteDB("note");
        
    }                                        

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
       
    }                                           

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
       
        
    }                                      

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {                                       
        // TODO add your handling code here:
        this.requestFocus();
    }                                      

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        
       idST =jTextField2.getText();
       
    }                                     

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
       
    }                                           

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        
    }                                           

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        Nom=jTextField3.getText();

    }                                     

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
         Pre=jTextField4.getText();
    }                                     

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        note=jTextField6.getText();
    }                                     

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        // TODO add your handling code here:
        
           //jComboBox1.setSelectedIndex(0);
           Branch=String.valueOf( jComboBox1.getSelectedItem());
               
           
       
    }                                           

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jTextField2.setEditable(true);
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
      // jComboBox1.setSelectedIndex(0);
        
        ArrayList<String> data =LireDB("Note");
    }                                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
       /* if(jTextField1.getText().length()==0){
            Model4.setRowCount(0);
            LireDB("note");
        }*/
        
    }                                       

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        NomET=jTextField1.getText();
        if(NomET.length()==0){
            Model3.setRowCount(0);
            LireDB("Note");
        }
    }                                     

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        idST=jTextField2.getText();
    }                                       

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        Nom=jTextField3.getText();
    }                                       

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
         Pre=jTextField4.getText();
    }                                       

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Branch=String.valueOf( jComboBox1.getSelectedItem());
    }                                          

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        Model6=(DefaultTableModel)jTable1.getModel();
        IndexRow =jTable1.getSelectedRow();
        idST =String.valueOf(Model6.getValueAt(IndexRow, 0));
    }                                    

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
       note=jTextField6.getText();

    }                                       

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration                   

 String idST ;
 String Nom ;
 String Pre ;
 String  note ;
 String Branch;
 String NomET;
 int IndexRow;
 String IDste;

    @Override
    public Connection connectionDB(String TableName) {
           try{ 
           Cnx=DriverManager.getConnection(conc, username, passwd);
              
             System.out.print("good");
             System.out.print("good connection");
             return Cnx;
             }
              catch(SQLException e ){
           e.printStackTrace();
              return null;}
           
       
    }

    @Override
    
    //LireDB pour afficher les donnée dans la table 
    public ArrayList<String>LireDB(String TableName) {
        int a =0;
            ArrayList<String> Data = new ArrayList<String>();
            String data[]=new String [5];

        Model2=(DefaultTableModel) jTable1.getModel();
        Model2.setRowCount(0);
         try{ 
        String l="select * from "+TableName;
          Cnx=connectionDB("Note");
          CreatST=Cnx.createStatement();
         Result= CreatST.executeQuery(l);
         
         while(Result.next())
             
           {
          String idST=Result.getString("idST");
          
          String Nom=Result.getString("nom");
           String Pre=Result.getString("prenom");
          String Branch=Result.getString("branch");
          String note=Result.getString("note");
              data[0]=   idST;
              data[1]=   Nom;
              data[2]=   Pre;
              data[3]=   Branch;
              data[4]=   note; 
              Model2.addRow(data);
              
              Data.add(idST);
              Data.add(Nom);
              Data.add(Pre);
              Data.add(Branch);
              Data.add(note);
                
           }
         return Data;
            
        }
          catch(SQLException e ){
           e.printStackTrace();
           return null;
             }
    }

    @Override
    //ajouter les donnée dans DataBase
    public void InsertDB(String TableName,String idST,String nom,String Prenom,String branch,String Note) {
      
         try{ 
          
          String l="insert into "+TableName+"(" +"idST"+","+"Nom"+","+"Prenom"+","+"Branch"+","+"Note"+")"+" VALUES"+"("+"\""+idST+"\""+","+"\""+nom+"\""+","+"\""+Prenom+"\""+"," +"\""+branch+"\""+","+"\""+Note+"\""+")";
          Cnx=connectionDB("Note");
          CreatST=Cnx.createStatement();
          CreatST.executeUpdate(l);  
         
        }
       catch(SQLException e ){
          System.out.print("la valeur est deja inclus dans la table ");
        // String l="insert into info VALUES"+"("+12+","+"\"simou\""+");";
         //System.out.print(l);
       }
    }
    
    //Function qui permet de modifier les donnée qui insere par utilusateur 
    public void UpdateDB(String TableName){
         try{
       
          String l="update "+TableName+" set nom="+"\""+this.Nom+"\""+","+" prenom="+"\""+this.Pre+"\""+"," +" branch="+"\""+this.Branch+"\""+","+" note="+"\""+this.note+"\""+" where idST="+"\""+this.idST+"\"";
          Cnx=connectionDB("Note");
          CreatST=Cnx.createStatement();
          CreatST.executeUpdate(l);  
         
        }
       catch(SQLException e ){
           e.printStackTrace();
       
       }
    }
    //Affichage data qui inserer par l'utulisateur   zone de cherche 
    public void recuperDATA(String tableName){
           Model3=(DefaultTableModel) jTable1.getModel();
           Model3.setRowCount(0);
        try{
             Cnx=connectionDB("Note");
             String sql ="select * from "+tableName+" where concat(nom,' ',prenom,'','idST','',note,'',branch) like"+"\""+"%"+NomET+"%"+"\"";
             CreatST=Cnx.createStatement();
             Result=CreatST.executeQuery(sql);
              String[] DATA =new String[5];
            
              while(Result.next()){
                 String nom=Result.getString("nom");
                 String Prenom=Result.getString("Prenom");
                 String idST=Result.getString("idST");
                 String branch=Result.getString("Branch");
                 String note=Result.getString("note");
                 
                 DATA[0]=idST;
                 DATA[1]=Prenom;
                 DATA[2]=nom;
                 
                 DATA[3]=branch;
                 DATA[4]=note;
                        
                                  
                Model3.addRow(DATA);
                 }
            
            
     
      
      
      }
     
     catch(SQLException e ){
         e.printStackTrace();
     }
     }
 //ajouter les données dans app après  le test si ID de ytilisateur est déja dans base de donnée 
public void  ModifyDB(String TableName){
    
    
    try{
             Cnx=connectionDB("Note");
             String sql ="select * from "+TableName+" where idst in ( "+"\""+IDste+"\""+","+"\""+idST+"\" )";
             CreatST=Cnx.createStatement();
             Result=CreatST.executeQuery(sql);
            
            
              while(Result.next()){
                  jTextField2.setText(Result.getString("idST"));
                  jTextField2.setEditable(false);
                  jTextField3.setText(Result.getString("nom"));
                  jTextField4.setText(Result.getString("Prenom"));
                
                 jComboBox1.addItem(Result.getString("Branch"));
                 jTextField6.setText(Result.getString("note"));
           
                 }
            
            
     
      
      
      }
     
     catch(SQLException e ){
         e.printStackTrace();
     }
}

    @Override
    public void DeleteDB(String TableName) {
     
    try{
             Cnx=connectionDB("Note");
             String l="delete from "+TableName+" where idST="+"\""+idST+"\"";
             CreatST=Cnx.createStatement();
             CreatST.executeUpdate(l);
             
             
         }
         catch(SQLException e){
             e.printStackTrace();
         }
    }
   
    
}
